### ISSUE TITLE
Is It Possible To Set Zoom Level For "about:newtab" Page?

### ISSUE THREAD

**Issue by KhunRoger** [jtackaberry/nosquint#125]
The title says it all  :)  :

Is it possible to set a zoom level for the "about:newtab" page in Firefox?

I have a small Netbook with a 1024 x 600 screen. My "about:newtab" page in Firefox is 5 columns by 6 rows of icons. I can't squeeze them all in without hitting Control-Minus a few times.

I've looked at NoSquint's "Exceptions" feature, but I don't think it applies.

The NoSquint status bar icon shows "N/A" for the "about:newtab" page.

Any help will be gratefully received!

Regards,

Roger.

**Comment by stefnotch** [comment]
Set browser.newtab.preload to false.

**Comment by KhunRoger** [comment]
It is already set to false.

**Comment by stefnotch** [comment]
So, does it work? When you change the zoom (Ctrl+minus), will it be remembered?

**Comment by KhunRoger** [comment]
What I meant was, it was already set to false and it has always been set to false. So "no". the zoom is not remembered.

I know about "browser.newtabpage.columns" and "browser.newtabpage.rows". Mine are 5 and 8 respectively.

**Comment by stefnotch** [comment]
Mine are 5 and 3. And, what Firefox version are you using? Firefox 38.0.1? Also, is the browser.newtab.preload bold?

**Comment by KhunRoger** [comment]
FF 28.0
Yes, the browser.newtab.preload  preference is bold, and false.

**Comment by stefnotch** [comment]
Well, you are using an outdated version of FF. And, when it is bold, it means that somebody/something such as an add-on changed it. You might want to try to update your FF and/or disable all add-ons and see if that makes a difference.

**Comment by KhunRoger** [comment]
Sorry for late response!! OK, thanks for your help.
