### ISSUE TITLE
No Squint makes pydio-based sites unusable

### ISSUE THREAD

**Issue by sognetic** [jtackaberry/nosquint#164]
Hi!

I just started using a file sharing tool similar to Dropbox called [pydio](pyd.io). Unfortunately, No Squint somehow breaks the My Account -> My Profile section, where there should normally be a form to enter your profile stuff there is nothing with No Squint. You can reproduce this behaviour with the demo tool on demo.pyd.io.

Thanks!

**Comment by jtackaberry** [comment]
On the demo site, under My Account / My Profile I see an empty page with or without NoSquint enabled, and even in Chrome.  Can you double check to see if you get what you expect with NoSquint disabled?

**Comment by sognetic** [comment]
Unfortunately, it seems like the demo-site has disabled the profile editor for understandable reasons. These are two pictures of my pydio-site, one with NoSquint disabled and the second one with NoSquint enabled:
![mysite_nosquint_disabled](https://cloud.githubusercontent.com/assets/10749132/6178558/60198f70-b310-11e4-93d6-053c290eed01.jpg)
![mysite_nosquint_enabled](https://cloud.githubusercontent.com/assets/10749132/6178557/60192396-b310-11e4-8227-1ffcec469ccb.jpg)
As you can see the whole white panel thing is missing once I activate NoSquint.

The effect is the same on the demo-site, they have just disabled the input fields:
![demo_pydio_nosquint_disabled](https://cloud.githubusercontent.com/assets/10749132/6178556/6017115a-b310-11e4-98f5-dd79a7c3dde2.jpg)
![demo_pydio_nosquint_enabled](https://cloud.githubusercontent.com/assets/10749132/6178555/601599f6-b310-11e4-82a2-fcf427e16bcb.jpg)

Thanks for looking into this! I really like your addon, it's great with a HiDPI screen.

**Comment by sognetic** [comment]
I just found out something: The error persist only on one specific zoom level (NoSquint or otherwise), I suspect it's pydio's fault. I blamed NoSquint because disabling NoSquint reset the zoom level, resulting in a functioning site again. Sorry to have bothered you, it's not your great addon's fault but pydio's.
