### ISSUE TITLE
Reset Firefox - No Squint icon doesn't show up

### ISSUE THREAD

**Issue by wjh48** [jtackaberry/nosquint#196]
Long story short - I had to reset Firefox and reinstall all my extensions, which included No Squint. I also have the Add-on Bar that used to show the No Squint icon in the lower right. Now it doesn't. I tried resetting all the No Squint extensions in the about:config page, but that didn't work.
Help, please!

thanks!

**Comment by streetwolf** [comment]
At the moment it seems NS is on hold.  I really hope Jason can get back to updating NS to work with Nightly.

**Comment by wjh48** [comment]
Thanks. Really weird, 'cause it was working fine until I started having some Firefox issues and did the refresh thing. Also having issues with a few other extensions as well. Maybe Mozilla can help.
